[build]
publish = "dist"
command = "npm run build:all"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/rails-omae-datta-no-ka"
to = "/rails-omae-datta-no-ka/"
status = 301

[[redirects]]
from = "/rails-omae-datta-no-ka/*"
to = "/rails-omae-datta-no-ka/index.html"
status = 200

[[redirects]]
from = "/test-slide"
to = "/test-slide/"
status = 301

[[redirects]]
from = "/test-slide/*"
to = "/test-slide/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
